---
title: "NZ_Map"
format: pdf
editor: visual
---

```{r,warning = FALSE, include=FALSE}
library(leaflet)
library(leaflet.extras)
library(sf)
library(ggplot2)
library(dplyr)
library(viridis)

```

Basic New Zealand Map

```{r echo=FALSE,warning=FALSE}
# Task 1: Creating a New Zealand map
NZ_map <- leaflet() %>%
addTiles() %>%
setView(lng = 176.87080273943093, lat = -41.141089622379005, zoom = 5)
# Display the basic map
NZ_map
```

Add Markers

```{r echo=FALSE,warning=FALSE}
# Task 2: Create New Zealand map dataset
NZ_pop <- data.frame(
city = c("Auckland", "Wellington", "Christchurch"),
lat = c(-36.852095, -41.2887953, -43.530955), lng = c(174.7631803, 174.7772114, 172.6364343), population = c(1614300, 207900, 375000))

# Create New Zealand map with marers
NZ_map_pop <- leaflet(NZ_pop) %>%
addTiles() %>%
setView(lng = 176.87080273943093, lat = -41.141089622379005, zoom = 5) %>%
addMarkers(~lng, ~lat, popup = ~paste(city, "<br>Population:", population))

# Display the map with markers
NZ_map_pop

```

Heat Map

```{r echo=FALSE,warning=FALSE}
# Task 3: Create a heatmap showing population density using the actual data
NZ_map_heatmap <- leaflet(NZ_pop) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  # Use the same readable tile
  addHeatmap(lng = ~lng, lat = ~lat, intensity = ~population) %>% addProviderTiles("OpenStreetMap.HOT")

# Display the heatmap
NZ_map_heatmap

```

				

**Read a .geoJSON file**

```{r echo=FALSE,warning=FALSE}
# Task 4: Read a .geoJSON file
geojson_data <- st_read("~/Desktop/nz_ta.geojson")
```

**Create a black and white plot with regions**

```{r echo=FALSE,warning=FALSE}
# Task: Create black and white plot of the regions
ggplot() +
  geom_sf(data = geojson_data, fill = "white", color = "black") +  # Use black and white
  theme_void()  # Remove background, gridlines, etc

```

Cleaning data

```{r echo = FALSE}
# Task 6: Read the CSV file
population_data <- read.csv("~/Desktop/nz_territory_2016_population.csv")
# Rename columns for clarity
colnames(population_data) <- c("nz_territory", "population", "population_change_number", "population_change_percent")

```
